<MyLayout>:
    orientation: "vertical"
    padding: 8

    GridLayout:
        cols: 3
        size_hint_y: 0.15
        BoxLayout:
            size_hint_x: 0.3
            orientation: "vertical"
            Label:
                id: weather_img
                text: ""
                size_hint_y: 0.6
                font_name: "EmojiFont"
                font_size: "27sp"
                text_size: self.size
            Label:
                id: weather_temp
                text: ""
                size_hint_y: 0.2
                font_size: "20sp"
                text_size: self.size
            Label:
                id: weather_desc
                text: ""
                size_hint_y: 0.2
                font_size: "20sp"
                text_size: self.size
        Label:
            id: header
            text: ""
            halign: "center"
            valign: "middle"
            font_size: "27sp"
            size_hint_x: 0.4
            bold: True
        Label:
            id: time
            text: ""
            font_size: "27sp"
            size_hint_x: 0.3
            bold: True

    BoxLayout:
        id: image_box
        size_hint_y: 0.35
        padding: 100
        # Obrazek
        Image:
            id: face_img
            source: "mask_full_smile.png"
            size_hint_y: 1

    # Box na dwa teksty
    BoxLayout:
        orientation: "vertical"
        size_hint_y: 0.5
        padding: [0, 150, 0, 0]
        spacing: 50

        Label:
            id: command
            text: ""
            font_size: "30sp"
            size_hint_y: 0.2
            halign: "center"
            valign: "middle"
            text_size: self.size
            wrap: True

        Label:
            id: model_response
            text: ""
            font_size: "30sp"
            size_hint_y: 0.8
            halign: "center"
            valign: "top"
            text_size: self.size
            wrap: True
        
        GridLayout:
            id: columns
            cols: 3
            size_hint_y: 0.0
            
            BoxLayout:
                orientation: "vertical"
                Label:
                    id: col1_img
                    text: ""
                    size_hint_y: 0.5
                    font_name: "EmojiFont"
                    halign: "center"
                    valign: "middle"
                    text_size: self.size
                Label:
                    id: col1_day
                    text:""
                    size_hint_y: 0.2
                    font_size: "30sp"
                    halign: "center"
                    valign: "middle"
                    text_size: self.size
                Label:
                    id: col1_desc
                    text:""
                    size_hint_y: 0.2
                    font_size: "25sp"
                    halign: "center"
                    valign: "middle"
                    text_size: self.size
                Label:
                    id: col1_H
                    text:""
                    size_hint_y: 0.1
                    font_size: "20sp"
                    halign: "center"
                    valign: "middle"
                    text_size: self.size
            
            BoxLayout:
                orientation: "vertical"
                Label:
                    id: col2_img
                    text: ""
                    size_hint_y: 0.5
                    font_name: "EmojiFont"
                    halign: "center"
                    valign: "middle"
                    text_size: self.size
                Label:
                    id: col2_day
                    text:""
                    size_hint_y: 0.2
                    font_size: "30sp"
                    halign: "center"
                    valign: "middle"
                    text_size: self.size
                Label:
                    id: col2_desc
                    text:""
                    size_hint_y: 0.2
                    font_size: "25sp"
                    halign: "center"
                    valign: "middle"
                    text_size: self.size
                Label:
                    id: col2_H
                    text:""
                    size_hint_y: 0.1
                    font_size: "20sp"
                    halign: "center"
                    valign: "middle"
                    text_size: self.size
                        
            BoxLayout:
                orientation: "vertical"
                Label:
                    id: col3_img
                    text: ""
                    size_hint_y: 0.5
                    font_name: "EmojiFont"
                    halign: "center"
                    valign: "middle"
                    text_size: self.size
                Label:
                    id: col3_day
                    text:""
                    size_hint_y: 0.2
                    font_size: "30sp"
                    halign: "center"
                    valign: "middle"
                    text_size: self.size
                Label:
                    id: col3_desc
                    text:""
                    size_hint_y: 0.2
                    font_size: "25sp"
                    halign: "center"
                    valign: "middle"
                    text_size: self.size
                Label:
                    id: col3_H
                    text:""
                    size_hint_y: 0.1
                    font_size: "20sp"
                    halign: "center"
                    valign: "middle"
                    text_size: self.size